config/routes.rb
Rails.application.routes.draw do


<<<<<<< HEAD
  resources :documents
=======
  resources :events
>>>>>>> events-feature
  resources :categories

  post '/attendances/create' => 'attendances#create', :as => :create_attendance
  resources :attendances

  get 'team/scaffold'

  resources :events do
    get :autocomplete_user_name, :on => :collection
  end

  resources :stakeholders

  resources :eadmin_tasks do
<<<<<<< HEAD
		  member do
		    patch :complete
		    patch :not_complete
		    patch :create
        patch :edit
		  end
		end
=======
    member do
      patch :complete
      patch :not_complete
      patch :create
    end
  end
>>>>>>> events-feature

  devise_for :views
  #Devise routes with custom registrations controller
  devise_for :users, controllers: { registrations: "registrations", sessions: "sessions" }

  resources :admin_tasks
  # get 'admin_tasks/:category' => 'admin_tasks#index'

  resources :users

  get 'users/:id/eadmin_tasks' => 'users#eadmin_tasks', :as => :user_eadmin_tasks
  get 'users/:id/promote_to_admin' => 'users#promote_to_admin', :as => :promote_user_to_admin
  get 'events/:id/attendance' => 'events#attendance', :as => :manage_event_attendance
  get "subscriptions/cancel_subscription" => "subscriptions#cancel_subscription"
  get "subscriptions/update_card" => "subscriptions#update_card"
  post "subscriptions/update_card_details" => "subscriptions#update_card_details"
  resources :subscriptions



  root to: "home#index"

  get "admin" => "admin_tasks#index"
  get "employees" => "users#index"
  get "new/employee" => "users#new"
  get "edit/employee" => "users#edit"



  get "etasks" => "eadmin_tasks#index"

  resources :teams



end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  has_many :admin_tasks
  has_many :eadmin_tasks
  has_many :attendances, dependent: :destroy
  has_many :events, through: :attendances

  belongs_to :team
  # belongs_to :categories
  belongs_to :role
  #after_create :set_buildings
  after_create :add_role_to_user


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable, :confirmable, :async

  before_validation :lowercase_values
  validates :email, :presence => true
  validate :email_is_unique, on: :create
  validate :subdomain_is_unique, on: :create
  after_validation :create_tenant
  after_create :create_account
  after_create :tell_stakeholders


  def confirmation_required?
    false
  end

  def name_plus_start
    "#{self.name} (#{self.start_date.to_formatted_s(:short)})"
  end

  #used for tasks... will eventually send out an email to the user.
  def send_reminder
    if has_role? :admin                                           # if user is admin
      User.where.not(id: self.id).each do |u|                     # select all other users
        if u.has_three_day_overdue_tasks?                         # if user has task over 3 days old
          NotificationMailer.tattle_tale(self, u).deliver_now
          puts "oh my god, #{u.email} has a task thats 3 days over due!"
        end
      end
    else
      if has_overdue_tasks?
        NotificationMailer.overdue_email(self).deliver_now
        puts "sent email to #{self.email}"
      end
    end
  end

  # Identify if user has outstanding tasks
  def has_overdue_tasks?
    start = self.start_date
    self.eadmin_tasks.where(completed: 0).each do |task|
      difference = task.due_date.to_i   # Get the number of days from start date
      if task.when_due == "Before"
        difference = difference * -1    # if it is "before", multiply it by negative 1
      end
      return true if (start + difference).past? # if task was due in the past, return true.
    end
    return false  # Return false if not
  end

  # Identify if user has outstanding tasks
  def has_three_day_overdue_tasks?
    start = start_date
    eadmin_tasks.where(completed: 0).each do |task|
      difference = task.due_date.to_i   # Get the number of days from start date
      if task.when_due == "Before"
        difference = difference * -1    # if it is "before", multiply it by negative 1
      end
      return true if (start + difference + 3).past? # if task is three days overdue, return true.
    end
    return false  # Return false if not
  end

  def percentage_of_completed_tasks
    tasks = eadmin_tasks.all.count # total number of tasks
    return 100 if tasks == 0
    completed = eadmin_tasks.where(completed: 1).count # total tasks completed
    return ((completed / tasks.to_d)*100).to_i
  end

  # Promote a user to an administrator, delete all eadmin tasks
  def promote_to_admin
    # user = User.find(uid)
    if self.has_role? :registered
      self.add_role :admin
      self.remove_role :registered
      self.eadmin_tasks.destroy_all
    end
  end

  private

  def self.with_role(role)
    my_role = Role.find_by_name(role)
    where(:role => my_role)
  end

  def lowercase_values
    self.subdomain.downcase!
  end
  #Email should be unique in the account model
  def email_is_unique
    #Do Not validate email if errors are already in devise or present.
    return false unless self.errors[:email].empty?

    unless Account.find_by_email(email).nil?
      errors.add(:email, "Email is already in use")
    end
  end

  #Subdomain should be unique
  def subdomain_is_unique
    if subdomain.present?
      unless Account.find_by_subdomain(subdomain).nil?
        errors.add(:subdomain, "is already used")
      end
    end

    if Apartment::Elevators::Subdomain.excluded_subdomains.include?(subdomain)
      errors.add(:subdomain, "is not a valid subdomain")
    end
  end


  #Creates accounta after new user account
  #Saves users email to account model
  def create_account
    account = Account.new(:email => email, :subdomain => subdomain)
    account.save!
  end

  def create_tenant
    return false unless self.errors.empty?
    #If its a new record, create the tenant
    #For Edits, do not create
    if self.new_record?
      Apartment::Tenant.create(subdomain)
    end
    #Change schema to the tenant
    Apartment::Tenant.switch!(subdomain)
  end

  def tell_stakeholders
    Stakeholder.all.each do |u|
      NotificationMailer.notify_stakeholder(u, self).deliver_later
    end
  end

  #Add default role to the user who signs up
  def add_role_to_user
    if created_by_invite?
      #Gives invited Employees default role.
      add_role :registered
      #copies admin task list to new eadmin task list for new inited employees
      id = self.id
      team = self.user_info

      ap 'ALL'
      ap team
      # ap AdminTask.where(team: team, "All")
      AdminTask.where(:team => team).each do |task|
        eadmin_tasks.create(
        title: task.title,
        description: task.description,
        media: task.media,
        due_date: task.due_date,
        when_due: task.when,
        category: task.category,
        document: task.document,
        team: self.user_info,
        user_id: id,
        completed: 0)
      end


      AdminTask.where(:team => "Everyone").each do |task|
        eadmin_tasks.create(
        title: task.title,
        description: task.description,
        media: task.media,
        due_date: task.due_date,
        when_due: task.when,
        category: task.category,
        document: task.document,
        team: "Everyone",
        user_id: id,
        completed: 0)
      end
    else
      add_role :admin
      id = self.id
      #Sets Default Teams for new users accounts.
      Team.create(:name => "Everyone")
      Team.create(:name => "HR")
      Team.create(:name => "IT")
      Team.create(:name => "Finance")
      #Sets Default Categories for new users accounts.
      Category.create(:name => "Paperwork",:team => "Everyone" )
      Category.create(:name => "Equipment & Tools", :team => "Everyone")
      Category.create(:name => "Meet the Company", :team => "Everyone")
      Category.create(:name => "Get Going", :team => "Everyone")

      #Sets Default Categories for new users accounts.
      Category.create(:name => "Paperwork",:team => "HR" )
      Category.create(:name => "Equipment & Tools", :team => "HR")
      Category.create(:name => "Meet the Company", :team => "HR")
      Category.create(:name => "Get Going", :team => "HR")
      #Sets Default Categories for new users accounts.
      Category.create(:name => "Paperwork",:team => "IT" )
      Category.create(:name => "Equipment & Tools", :team => "IT")
      Category.create(:name => "Meet the Company", :team => "IT")
      Category.create(:name => "Get Going", :team => "IT")
      #Sets Default Categories for new users accounts.
      Category.create(:name => "Paperwork",:team => "Finance" )
      Category.create(:name => "Equipment & Tools", :team => "Finance")
      Category.create(:name => "Meet the Company", :team => "Finance")
      Category.create(:name => "Get Going", :team => "Finance")
      # Crates default tasks on a new account.

      #Paperwork Everyone
      AdminTask.create( :team => "Everyone", :title => "Your Contract ", :description => "Please view and sign your contract. f you have any issues please contact X at X@yourcompany.com", :when => "Before", :due_date => "5", :category  => "Paperwork", )
      AdminTask.create( :team => "Everyone", :title => "Data Privacy Agreement ", :description => "Please view and sign our data privacy agreement.", :when => "Before", :due_date => "5", :category  => "Paperwork", )
      AdminTask.create( :team => "Everyone", :title => "Health Insurance Enrollment Form", :description => "Please fill out this health insurance enrollment form", :when => "Before", :due_date => "5", :category  => "Paperwork",)
      AdminTask.create( :team => "Everyone", :title => "Sexual Harassment Policy ", :description => "Please read the attached sexual harassment policy.", :when => "Before", :due_date => "5", :category  => "Paperwork",)
      AdminTask.create( :team => "Everyone", :title => "Employee Manual", :description => "Please read the attached employee handbook.", :when => "Before", :due_date => "5", :category  => "Paperwork",)


      #Paperwork HR
      AdminTask.create( :team => "HR", :title => "Your Contract", :description => "Please view and sign your contract. f you have any issues please contact X at X@yourcompany.com", :when => "Before", :due_date => "5", :category  => "Paperwork", )
      AdminTask.create( :team => "HR", :title => "Data Privacy Agreement", :description => "Please view and sign our data privacy agreement.", :when => "Before", :due_date => "5", :category  => "Paperwork", )
      AdminTask.create( :team => "HR", :title => "Health Insurance Enrollment Form", :description => "Please fill out this health insurance enrollment form", :when => "Before", :due_date => "5", :category  => "Paperwork",)
      AdminTask.create( :team => "HR", :title => "Sexual Harassment Policy", :description => "Please read the attached sexual harassment policy.", :when => "Before", :due_date => "5", :category  => "Paperwork",)
      AdminTask.create( :team => "HR", :title => "Employee Manual", :description => "Please read the attached employee handbook.", :when => "Before", :due_date => "5", :category  => "Paperwork",)
      AdminTask.create( :team => "HR", :title => "Employee Details Form", :description => "Please fill out the attached employee details form with info about your bank a/c and preferred payment frequency.", :when => "Before", :due_date => "5", :category  => "Paperwork",)

      #Paperwork IT

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!
  load_and_authorize_resource

  def index
    @users = User.all

  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
    @team = Team.where.not(name: 'Everyone')
  end

  def edit
    @user = User.find(params[:id])
    @team = Team.where.not(name: 'Everyone')
  end

  def eadmin_tasks
    @user = User.find(params[:id])

    my_id_param = params[:id]

    # @paperwork_link = 'Paperwork<span class="badge">'+@user.eadmin_tasks.where(:category => "Paperwork").where(:completed => [nil, 0]).count.to_s+'</span>'
    # @eat_link = 'Equipment &amp; Tools<span class="badge">'+@user.eadmin_tasks.where(:category => "Equipment & Tools").where(:completed => [nil, 0]).count.to_s+'</span>'
    # @mtc_link = 'Meet the Company<span class="badge">'+@user.eadmin_tasks.where(:category => "Meet the Company").where(:completed => [nil, 0]).count.to_s+'</span>'
    # @getgoing_link = 'Get Going<span class="badge">'+@user.eadmin_tasks.where(:category => "Get Going").where(:completed => [nil, 0]).count.to_s+'</span>'
<<<<<<< HEAD
    @categories = Category.where(:team => @user.user_info)
    @categories_all = Category.where(:team => "Everyone")

=======
    @categories = Category.where(:team => current_user.user_info)
    @categories_all = Category.where(:team => "All")
    @events = Event.includes(:users).where(users: {id: params[:id]})
>>>>>>> events-feature

    if params[:category]
      ap "Option 1"
      @eadmin_tasks = EadminTask.where(:category => params[:category], :user_id => my_id_param).where( :team => params[:team])

    else
      ap "Option 2"
      redirect_to :controller => 'users', :action => 'eadmin_tasks', :category => Category.where(:team => "Everyone").first.name, :team => "Everyone"

    end

  end



  def create
    @user = User.new(user_params)
    @eadmin_tasks = AdminTask.all

    if @user.save
      redirect_to @user, :flash => { :success => 'Employee was successfully created.' }
    else
      render :action => 'new'
    end
  end


  def new_eadmin

    @eadmin_task = current_user.eadmin_tasks.build
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(user_params)
      sign_in(@user, :bypass => true) if @user == current_user
      redirect_to users_path, :flash => { :success => 'User was successfully updated.' }
    else
      render :action => 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    ap @eadmin_tasks = EadminTask.where(:user_id => @user.id)
    @eadmin_tasks.destroy_all
    redirect_to users_path, :flash => { :success => 'User was successfully deleted.' }
  end

  def promote_to_admin
    @user = User.find(params[:id])
    @user.promote_to_admin
    redirect_to users_path, notice: "They are now an admin!"
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :name, :user_info, :start_date)
  end
  def eadmin_task_params
    params.require(:eadmin_task).permit(:title, :description, :media, :due_date, :category, :when_due)
  end
end

app/views/users/eadmin_tasks.html.erb
<!-- Admin Tools -->

<div class="fixed-action-btn" style="bottom: 45px; right: 24px;">
  <% if params[:category] %>
    <%= link_to '<i class="large material-icons">add</i>'.html_safe, new_eadmin_task_path(:category => params[:category], :user_id => params[:id]), id: "addSmallButton", class: "btn-floating btn-large teal tooltipped", 'data-tooltip': "Add Task", 'data-position': "left" %>
  <% else %>
    <%= link_to '<i class="large material-icons">add</i>'.html_safe, new_eadmin_task_path(:category => "Paperwork", :user_id => params[:id]), id: "addSmallButton", class: "btn-floating btn-large teal tooltipped", 'data-tooltip': "Add Task", 'data-position': "left" %>
  <% end %>
  <!-- <a href="add.html" class="btn-floating btn-large red tooltipped" data-position="left" data-tooltip="Add Task">
    <i class="large material-icons">add</i>
  </a> -->
  <!-- <ul>
    <li><a class="btn-floating yellow darken-1 tooltipped" data-position="left" data-tooltip="Manage Users"><i class="material-icons">perm_identity</i></a></li>
    <li><a class="btn-floating green tooltipped" data-position="left" data-tooltip="Edit Template"><i class="material-icons">recent_actors</i></a></li>
    <li><a class="btn-floating blue tooltipped" data-position="left" data-tooltip="Manage Account Settings"><i class="material-icons">settings</i></a></li>
  </ul> -->
</div>
<!-- End admin tools -->



<!-- Wrapper for sidebar and layout -->

<div class="row">
<<<<<<< HEAD

=======
  <!-- Sidebar -->
  <div class="col s12 m4 l3">
    <!-- Profile card -->
    <div class="card top">
      <div class="card-content">
        <span class="card-title"><%= @user.name %></span>
        <p>Here you can see, add, and delete tasks for <%= @user.name %>. Make their first days with your company unforgettable!</p>
      </div>
    </div>


    <div class="collection">
      <% @categories_all.each do |category| %>
          <%= link_to category.name, params.merge(:category => category.name), class: "collection-item"%>
      <% end %>
      <% @categories.each do |category| %>
        <%= link_to category.name, params.merge(:category => category.name), class: "collection-item"%>
      <% end %>
    </div>

    <% unless @events.empty? %>
    <ul class="collection">
      <% @events.each do |e| %>
      <% attendance = Attendance.where(event_id: e.id).where(user_id: @user.id).first %>
      <%# attendance = @events.includes(:attendances).where(attendances: {event_id: e.id}).first %>
        <li class="collection-item"><div><%= e.name %><%= link_to '<i class="material-icons">send</i>'.html_safe, edit_attendance_path(:id => attendance.id), class: "secondary-content" %></div></li>
      <% end %>
    </ul>
    <% end %>

  </div>
  <!-- End Sidebar -->
>>>>>>> events-feature

  <!-- Content -->
  <div class="col s12 m7 l7 offset-l1">
    <div class="row top">
      <% if params[:category] %>
        <h4 style="display: inline"><%=params[:category]%> Tasks</h4>
      <% else %>
        <h4 style="display: inline"><%= @categories_all.first.name %> Tasks</h4>
      <% end %>

      <% if params[:category] %>
        <%= link_to '<i class="material-icons left">add</i>Add a new task</a>'.html_safe, new_eadmin_task_path(:user_id => params[:id], :category => params[:category], :team => params[:team]), id: "addBigButton", class: "waves-effect waves-light btn show-on-large", style: "float: right"  %>
      <% else %>
        <%= link_to '<i class="material-icons left">add</i>Add a new task</a>'.html_safe, new_eadmin_task_path(:user_id => params[:id], :category => @categories_all.first.name ), id: "addBigButton", class: "waves-effect waves-light btn show-on-large", style: "float: right" %>
      <% end %>
    </div>

<<<<<<< HEAD
=======
    <div class="row">
      <ul class="tabs">
        <li class="tab"><a class="active" href="#test1">Tasks</a></li>
        <li class="tab"><a href="#test2">Helpful Documents</a></li>
      </ul>
    </div>
>>>>>>> events-feature

    <% if @eadmin_tasks.empty? %>
    <div class="row centered">
      <div class="col s12 m6">
        <div class="card-panel teal">
          <span class="white-text">
            <i class="em em-sweat_smile"></i> Looks like <%= @user.name %> doesn't have any tasks here! You can add one by clicking the big green button!
          </span>
        </div>
      </div>
    </div>
    <% end %>



    <% unless @eadmin_tasks.where(:when_due => "Before").where(:completed => 0).empty? %>
      <h5 class="top">Before they start...</h5>
    <% end %>

    <% @eadmin_tasks.order( 'eadmin_tasks.created_at ASC','eadmin_tasks.due_date DESC' ).each do |eadmin_task| %>
      <% if eadmin_task.when_due == "Before" && eadmin_task.completed? == false %>
        <!-- Card -->
        <div class="card hoverable">
          <div class="card-content">
            <span class="card-title activator grey-text text-darken-4"><%= eadmin_task.title %><i class="material-icons right">more_vert</i></span>
            <p><%= truncate(eadmin_task.description, length: 140, separator: ' ') %></p>
          </div>
          <div class="card-reveal">
            <span class="card-title grey-text text-darken-4"><%= eadmin_task.title %><i class="material-icons right">close</i></span>
            <p><%= eadmin_task.description %></p>
            <% if eadmin_task.document_file_name %>
              <p><%= link_to eadmin_task.document_file_name, eadmin_task.document.url(:original, false), :target => "_blank" %></p>
            <% end %>
          </div>
          <div class="card-action">
            <!-- <% if params[:category] %>
            <%= link_to 'edit', edit_eadmin_task_path(eadmin_task,:user_id => params[:id],:category => params[:category]), class: "blue-text" %>
            <% else %>
            <%= link_to 'edit', edit_eadmin_task_path(eadmin_task,:user_id => params[:id],:category => "Paperwork"), class: "blue-text" %>
            <% end %> -->
            <%= link_to 'edit', edit_eadmin_task_path(eadmin_task, :category => params[:category], :team => params[:team], :user_id => params[:id]), class: "blue-text" %>

            <%= link_to 'delete', eadmin_task, method: :delete, class: "blue-text", data: { confirm: 'Are you sure you want to delete this task?' } %>
            <span class="right"><%= eadmin_task.due_date %> <%= eadmin_task.due_date == 1 ? "day" : "days" %> <%= eadmin_task.when_due.downcase %> they start</span>
          </div>
        </div>
        <!-- End card -->
      <%end%>
    <%end%>



    <% unless @eadmin_tasks.where(:when_due => "After").where(:completed => 0).empty? %>
      <h5 class="top">After they start...</h5>
    <% end %>

    <% @eadmin_tasks.order( 'eadmin_tasks.created_at ASC', 'eadmin_tasks.due_date DESC' ).each do |eadmin_task| %>
      <% if eadmin_task.when_due == "After" && eadmin_task.completed? == false %>
        <!-- Card -->
        <div class="card hoverable grey lighten-2">
          <div class="card-content">
            <span class="card-title activator grey-text text-darken-4"><%= eadmin_task.title %><i class="material-icons right">more_vert</i></span>
            <p><%= truncate(eadmin_task.description, length: 140, separator: ' ') %></p>
          </div>
          <div class="card-reveal grey lighten-2">
            <span class="card-title grey-text text-darken-4"><%= eadmin_task.title %><i class="material-icons right">close</i></span>
            <p><%= eadmin_task.description %></p>
            <% if eadmin_task.document_file_name %>
              <p><%= link_to eadmin_task.document_file_name, eadmin_task.document.url(:original, false), :target => "_blank" %></p>
            <% end %>
          </div>
          <div class="card-action">
            <!-- <% if params[:category] %>
            <%= link_to 'edit', edit_eadmin_task_path(eadmin_task,:user_id => params[:id],:category => params[:category]), class: "blue-text" %>
            <% else %>
            <%= link_to 'edit', edit_eadmin_task_path(eadmin_task,:user_id => params[:id],:category => "Paperwork"), class: "blue-text" %>
            <% end %> -->
            <%= link_to 'delete', eadmin_task, method: :delete, class: "blue-text", data: { confirm: 'Are you sure you want to delete this task?' } %>
              <span class="right"><%= eadmin_task.due_date %> <%= eadmin_task.due_date == 1 ? "day" : "days" %> <%= eadmin_task.when_due.downcase %> they start</span>
          </div>
        </div>
        <!-- End card -->
      <%end%>
    <%end%>




    <% unless @eadmin_tasks.where(:completed => 1).empty? %>
      <h5 class="top">Recently Completed</h5>
    <% end %>

    <% @eadmin_tasks.order( 'eadmin_tasks.created_at ASC', 'eadmin_tasks.due_date DESC' ).each do |eadmin_task| %>
      <% if eadmin_task.completed? %>
        <!-- Card -->
        <div class="card hoverable #b2dfdb teal lighten-4">
          <div class="card-content">
            <span class="card-title activator grey-text text-darken-4"><%= eadmin_task.title %><i class="material-icons right">more_vert</i></span>
            <p><%= truncate(eadmin_task.description, length: 140, separator: ' ') %></p>
          </div>
          <div class="card-reveal #b2dfdb teal lighten-4">
            <span class="card-title grey-text text-darken-4"><%= eadmin_task.title %><i class="material-icons right">close</i></span>
            <p><%= eadmin_task.description %></p>
            <% if eadmin_task.document_file_name %>
              <p><%= link_to eadmin_task.document_file_name, eadmin_task.document.url(:original, false), :target => "_blank" %></p>
            <% end %>
          </div>
          <div class="card-action">
            <!-- <% if params[:category] %>
            <%= link_to 'edit', edit_eadmin_task_path(eadmin_task,:user_id => params[:id],:category => params[:category]), class: "blue-text" %>
            <% else %>
            <%= link_to 'edit', edit_eadmin_task_path(eadmin_task,:user_id => params[:id],:category => "Paperwork"), class: "blue-text" %>
            <% end %> -->
            <%= link_to 'delete', eadmin_task, method: :delete, class: "blue-text", data: { confirm: 'Are you sure you want to delete this task?' } %>
            <span class="right"><%= eadmin_task.due_date %> <%= eadmin_task.due_date == 1 ? "day" : "days" %> <%= eadmin_task.when_due.downcase %> they start</span>
          </div>
        </div>
        <!-- End card -->
      <%end%>
    <%end%>

  </div>
  <!-- End content -->

  <!-- Sidebar -->
  <div class="col s12 m3 l3 offset-l1">
    <!-- Profile card -->
    <div class="card top">
      <div class="card-content">
        <span class="card-title"><%= @user.name %></span>
        <p>Here you can see, add, and delete tasks for <%= @user.name %>. Make their first days with your company unforgettable!</p>
      </div>
    </div>


    <h5>Tasks for Everyone</h5>
    <div class="collection">
      <% @categories_all.each do |category| %>
          <%= link_to category.name, params.merge(:category => category.name, :team => "Everyone"), class: "collection-item"%>
      <% end %>
    </div>
    <h5>Team Tasks</h5>
    <div class="collection">
      <% @categories.each do |category| %>
          <%= link_to category.name, params.merge(:category => category.name, :team => @user.user_info), class: "collection-item"%>
      <% end %>
    </div>

  </div>
  <!-- End Sidebar -->
</div>

app/views/users/edit.html.erb
<div class="row">
  <!-- spaceholder -->
  <div class="col s12 m12 l2">&nbsp;</div>
  <div class="col s12 m12 l8">
    <div class="top centered"><h3>Edit a New Hire</h3></div>
    <%= render 'form' %>
    <div class="centered"><p><%= link_to 'Make this person an admin', promote_user_to_admin_path %></p></div>
  </div>
  <!-- spaceholder -->
  <div class="col s12 m12 l2">&nbsp;</div>
</div>

<script>
 $('.datepicker').pickadate({
    selectMonths: true, // Creates a dropdown to control month
    selectYears: 15 // Creates a dropdown of 15 years to control year
  });

</script>

app/views/users/index.html.erb
<div class="row">
  <!-- spaceholder -->
  <div class="col s12 m12 l2">&nbsp;</div>
  <!-- form -->
  <div class="col s12 m12 l8">
    <div class="row top">
      <h4 style="display: inline">Manage Employees</h4>
      <%= link_to '<i class="material-icons left">add</i>Invite a New Hire</a>'.html_safe, new_user_invitation_path, class: "waves-effect waves-light btn-large", style: "float: right" %>
      <br /><br /><%= link_to 'Who else needs to know the new hires?', stakeholders_path %>
    </div>
    <div class="row">
      <ul class="collection">
        <% @users.each do |user| %>
          <% if user.has_role? :registered%>
            <% if user.has_three_day_overdue_tasks? %>
              <li class="collection-item avatar red lighten-4">
            <% elsif user.has_overdue_tasks? %>
              <li class="collection-item avatar yellow lighten-4">
            <% else %>
              <li class="collection-item avatar">
            <% end %>
              <div style="position: absolute; overflow: hidden; left: 15px; display: inline-block; vertical-align: middle;">
                <% percent = user.percentage_of_completed_tasks.to_s %>
                <div class="c100 p<%= percent %> small left-align">
                  <span><%= percent %>%</span>
                  <div class="slice">
                    <div class="bar"></div>
                    <div class="fill"></div>
                  </div>
                </div>
              </div>
              <span class="title"><%= user.name %></span> - <%= user.user_info%> Team <br>
              <p><a href="mailto:<%= user.email %>"><%= user.email %></a> <br>

                <%= link_to 'Edit tasks &rarr;'.html_safe, user_eadmin_tasks_path(:id => user.id) %>

              </p>
              <div class="secondary-content">
                <%= link_to '<i class="material-icons">mode_edit</i>'.html_safe, edit_user_path(user) %>&ensp;&ensp;
                <%= link_to '<i class="material-icons">delete</i>'.html_safe, user, method: :delete, data: { confirm: 'Are you sure you want to delete this user?' } %>
                <p class="right-align grey-text"><%= user.start_date%></p>
              </div>
            </li>
          <% end %>
        <% end %>
      </ul>
    </div>
  </div>
  <!-- spaceholder -->
  <div class="col s12 m12 l2">&nbsp;</div>
</div>