config/routes.rb
Rails.application.routes.draw do


<<<<<<< HEAD
  resources :documents
=======
  resources :events
>>>>>>> events-feature
  resources :categories

  post '/attendances/create' => 'attendances#create', :as => :create_attendance
  resources :attendances

  get 'team/scaffold'

  resources :events do
    get :autocomplete_user_name, :on => :collection
  end

  resources :stakeholders

  resources :eadmin_tasks do
<<<<<<< HEAD
		  member do
		    patch :complete
		    patch :not_complete
		    patch :create
        patch :edit
		  end
		end
=======
    member do
      patch :complete
      patch :not_complete
      patch :create
    end
  end
>>>>>>> events-feature

  devise_for :views
  #Devise routes with custom registrations controller
  devise_for :users, controllers: { registrations: "registrations", sessions: "sessions" }

  resources :admin_tasks
  # get 'admin_tasks/:category' => 'admin_tasks#index'

  resources :users

  get 'users/:id/eadmin_tasks' => 'users#eadmin_tasks', :as => :user_eadmin_tasks
  get 'users/:id/promote_to_admin' => 'users#promote_to_admin', :as => :promote_user_to_admin
  get 'events/:id/attendance' => 'events#attendance', :as => :manage_event_attendance
  get "subscriptions/cancel_subscription" => "subscriptions#cancel_subscription"
  get "subscriptions/update_card" => "subscriptions#update_card"
  post "subscriptions/update_card_details" => "subscriptions#update_card_details"
  resources :subscriptions



  root to: "home#index"

  get "admin" => "admin_tasks#index"
  get "employees" => "users#index"
  get "new/employee" => "users#new"
  get "edit/employee" => "users#edit"



  get "etasks" => "eadmin_tasks#index"

  resources :teams



end

app/models/event.rb
class Event < ActiveRecord::Base
  # Associations
  belongs_to :team
  has_many :attendances
  has_many :users, through: :attendances

  attr_accessor :user_name

  # Named Scopes
  scope :within_week, lambda {where(:event_date  => Time.now..1.week.from_now).order('event_date ASC')}
  scope :within_month, lambda {where(:event_date => 1.week.from_now..1.month.from_now).order('event_date ASC')}
  scope :next_month, lambda {where(:event_date => 1.month.from_now..2.months.from_now).order('event_date ASC')}
  scope :after_2_months, lambda {where('event_date > ?', 2.months.from_now).order('event_date ASC')}




end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  autocomplete :user, :name, :full => true#, :extra_data => [:start_date]#, :display_value => :name_plus_start

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # GET /events/1/attendance
  def attendance
    @current_event = Event.find(params[:id])
    @users = User.includes(:events).where(events: {id: params[:id]})
    @employees = User.all.order(:name)
    @attendance = Attendance.new
  end


  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to events_path, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to events_path, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :organizer, :organizer_email, :location, :event_date, :team_id)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<div class="row">
  <!-- spaceholder -->
  <div class="col s12 m12 l2">&nbsp;</div>
  <div class="col s12 m12 l8">
    <%= form_for(@event) do |f| %>
      <% if @event.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

          <ul>
          <% @event.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= f.label :name %><br>
        <%= f.text_field :name %>
      </div>
      <div class="field">
        <%= f.label :organizer %><br>
        <%= f.text_field :organizer %>
      </div>
      <div class="field">
        <%= f.label :organizer_email %><br>
        <%= f.text_field :organizer_email %>
      </div>
      <div class="field">
        <%= f.label :location %><br>
        <%= f.text_field :location %>
      </div>
      <div class="field">
        <%= f.label :event_date %><br>
        <%= f.text_field :event_date, class: "datepicker" %>
      </div>
      <div class="field">
        <%= f.label :team_id %><br>
        <%= f.text_field :team_id %>
      </div>
      <div class="actions col s12 centered">
        <%= link_to 'Cancel', :back, class: "btn btn-large" %>
        <input type="submit" value="Submit!" class="btn btn-large" >
      </div>
    <% end %>
  </div>
  <!-- spaceholder -->
  <div class="col s12 m12 l2">&nbsp;</div>
</div>

app/views/events/attendance.html.erb
<!-- Header -->
<div class="row">
  <!-- spaceholder -->
  <div class="col s12 m12 l2">&nbsp;</div>
  <!-- form -->
  <div class="col s12 m12 l8">
    <div class="row top">
      <h4 class="center-align">Attendees for <%= @current_event.name %></h4>
    </div>
  </div>
  <!-- spaceholder -->
  <div class="col s12 m12 l2">&nbsp;</div>
</div>

<div class="row">
    <div class="col s12 m4 l4">
      <h5 class="center-align">Attending</h5>
      <% if @users.includes(:attendances).where(attendances: {rsvp: "Going"}).references(:attendances).empty? %>
        <p>Nobody is attending... (yet!)</p>
      <% elsif %>
        <% @users.includes(:attendances).where(attendances: {rsvp: "Going"}).references(:attendances).each do |u| %>
        <div class="chip">
          <%= u.name %> (<%= u.email %>)
        </div>
        <% end %>
      <% end %>
    </div>
    <div class="col s12 m4 l4">
      <h5 class="center-align">Not Attending</h5>
      <% if @users.includes(:attendances).where(attendances: {rsvp: "Not Going"}).references(:attendances).empty? %>
        <p>So far so good! Nobody is saying no!</p>
      <% elsif %>
        <% @users.includes(:attendances).where(attendances: {rsvp: "Not Going"}).references(:attendances).each do |u| %>
        <div class="chip">
          <%= u.name %> (<%= u.email %>)
        </div>
        <% end %>
      <% end %>
    </div>
    <div class="col s12 m4 l4">
      <h5 class="center-align">Invited</h5>
      <% if @users.includes(:attendances).where(attendances: {rsvp: "Invited"}).references(:attendances).empty? %>
        <p>Either everybody has RSVP'd, or you have some inviting to do!</p>
      <% elsif %>
        <% @users.includes(:attendances).where(attendances: {rsvp: "Invited"}).references(:attendances).each do |u| %>
        <div class="chip">
          <%= u.name %> (<%= u.email %>)
        </div>
        <% end %>
      <% end %>
    </div>
</div>

<%# This is the glory section. Making this work separates boys from men. %>
<div class="row">
  <div class="col s12 m12 l2">&nbsp;</div>
  <div class="col s12 m12 l8">
    <h5 class="top centered">Invite people to <%= @current_event.name %></h5>
    <%= form_for @attendance, :url => create_attendance_path do |f| %>
      <%= f.select :user_id, User.all.order(:name).collect { |u| [ u.name, u.id ] }, :multiple => true, include_blank: true %>
      <%= f.hidden_field(:event_id, :value => @current_event.id)%>
      <%= f.hidden_field(:rsvp, :value => "Invited")%>
      <div class="actions centered">
        <%= f.submit 'Invite!', class: "btn btn-large"%>
      </div>
    <% end %>
  </div>
  <div class="col s12 m12 l2">&nbsp;</div>
</div>

app/views/events/edit.html.erb
<div class="top centered"><h3>Edit this event</h3></div>
<%= render 'form' %>

app/views/events/index.html.erb
<!-- Header -->
<div class="row">
  <!-- spaceholder -->
  <div class="col s12 m12 l2">&nbsp;</div>
  <!-- form -->
  <div class="col s12 m12 l8">
    <div class="row top">
      <h3 style="display: inline">Manage Events</h3>
      <%= link_to 'Add an Event', new_event_path, class: "btn btn-large", style: "float: right" %>
    </div>
  </div>
  <!-- spaceholder -->
  <div class="col s12 m12 l2">&nbsp;</div>
</div>

<!-- Within the week -->
<% unless @events.within_week.empty? %>
<div class="row">
  <h5>Events within a week...</h5>
  <% @events.within_week.each do |event| %>
  <div class="col s12 m6 l6">
    <div class="card blue-grey darken-1">
      <div class="card-content white-text">
        <span class="card-title"><%= event.name %></span>
        <p>
          <a href="mailto:<%= event.organizer_email %>" class="white-text" style="text-decoration: underline"><%= event.organizer %></a> will be running this event on <%= event.event_date.to_formatted_s(:rfc822) %>.
          It will be held at <%= event.location %>.
        </p>
      </div>
      <div class="card-action">
        <%= link_to 'Edit', edit_event_path(event) %>
        <%= link_to 'Delete', event, method: :delete, data: { confirm: 'Are you sure?' } %>
        <%= link_to 'Manage Invites', manage_event_attendance_path(:id => event), style: 'float:right' %>
        <!-- <a href="#" style="float:right">Invite employees</a> -->
      </div>
    </div>
  </div>
  <% end %>
</div>
<% end %>

<!-- Within the month -->
<% unless @events.within_month.empty? %>
<div class="row">
  <h5>Later within a month...</h5>
  <% @events.within_month.each do |event| %>
  <div class="col s12 m6 l6">
    <div class="card blue-grey darken-1">
      <div class="card-content white-text">
        <span class="card-title"><%= event.name %></span>
        <p>
          <a href="mailto:<%= event.organizer_email %>" class="white-text" style="text-decoration: underline"><%= event.organizer %></a> will be running this event on <%= event.event_date.to_formatted_s(:rfc822) %>.
          It will be held at <%= event.location %>.
        </p>
      </div>
      <div class="card-action">
        <%= link_to 'Edit', edit_event_path(event) %>
        <%= link_to 'Delete', event, method: :delete, data: { confirm: 'Are you sure?' } %>
        <%= link_to 'Manage Invites', manage_event_attendance_path(:id => event), style: 'float:right' %>
      </div>
    </div>
  </div>
  <% end %>
</div>
<% end %>

<!-- Next month -->
<% unless @events.next_month.empty? %>
<div class="row">
  <h5>Events next month...</h5>
  <% @events.next_month.each do |event| %>
  <div class="col s12 m6 l6">
    <div class="card blue-grey darken-1">
      <div class="card-content white-text">
        <span class="card-title"><%= event.name %></span>
        <p>
          <a href="mailto:<%= event.organizer_email %>" class="white-text" style="text-decoration: underline"><%= event.organizer %></a> will be running this event on <%= event.event_date.to_formatted_s(:rfc822) %>.
          It will be held at <%= event.location %>.
        </p>
      </div>
      <div class="card-action">
        <%= link_to 'Edit', edit_event_path(event) %>
        <%= link_to 'Delete', event, method: :delete, data: { confirm: 'Are you sure?' } %>
        <%= link_to 'Manage Invites', manage_event_attendance_path(:id => event), style: 'float:right' %>
      </div>
    </div>
  </div>
  <% end %>
</div>
<% end %>

<!-- Within the month -->
<% unless @events.after_2_months.empty? %>
<div class="row">
  <h5>Later in the future...</h5>
  <% @events.after_2_months.each do |event| %>
  <div class="col s12 m6 l6">
    <div class="card blue-grey darken-1">
      <div class="card-content white-text">
        <span class="card-title"><%= event.name %></span>
        <p>
          <a href="mailto:<%= event.organizer_email %>" class="white-text" style="text-decoration: underline"><%= event.organizer %></a> will be running this event on <%= event.event_date.to_formatted_s(:rfc822) %>.
          It will be held at <%= event.location %>.
        </p>
      </div>
      <div class="card-action">
        <%= link_to 'Edit', edit_event_path(event) %>
        <%= link_to 'Delete', event, method: :delete, data: { confirm: 'Are you sure?' } %>
        <%= link_to 'Manage Invites', manage_event_attendance_path(:id => event), style: 'float:right' %>
      </div>
    </div>
  </div>
  <% end %>
</div>
<% end %>

app/views/events/new.html.erb
<div class="top centered"><h3>Create a New Event</h3></div>
<%= render 'form' %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @event.name %>
</p>

<p>
  <strong>Organizer:</strong>
  <%= @event.organizer %>
</p>

<p>
  <strong>Organizer email:</strong>
  <%= @event.organizer_email %>
</p>

<p>
  <strong>Location:</strong>
  <%= @event.location %>
</p>

<p>
  <strong>Event date:</strong>
  <%= @event.event_date %>
</p>

<p>
  <strong>Team:</strong>
  <%= @event.team %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>