config/routes.rb
Rails.application.routes.draw do


<<<<<<< HEAD
  resources :documents
=======
  resources :events
>>>>>>> events-feature
  resources :categories

  post '/attendances/create' => 'attendances#create', :as => :create_attendance
  resources :attendances

  get 'team/scaffold'

  resources :events do
    get :autocomplete_user_name, :on => :collection
  end

  resources :stakeholders

  resources :eadmin_tasks do
<<<<<<< HEAD
		  member do
		    patch :complete
		    patch :not_complete
		    patch :create
        patch :edit
		  end
		end
=======
    member do
      patch :complete
      patch :not_complete
      patch :create
    end
  end
>>>>>>> events-feature

  devise_for :views
  #Devise routes with custom registrations controller
  devise_for :users, controllers: { registrations: "registrations", sessions: "sessions" }

  resources :admin_tasks
  # get 'admin_tasks/:category' => 'admin_tasks#index'

  resources :users

  get 'users/:id/eadmin_tasks' => 'users#eadmin_tasks', :as => :user_eadmin_tasks
  get 'users/:id/promote_to_admin' => 'users#promote_to_admin', :as => :promote_user_to_admin
  get 'events/:id/attendance' => 'events#attendance', :as => :manage_event_attendance
  get "subscriptions/cancel_subscription" => "subscriptions#cancel_subscription"
  get "subscriptions/update_card" => "subscriptions#update_card"
  post "subscriptions/update_card_details" => "subscriptions#update_card_details"
  resources :subscriptions



  root to: "home#index"

  get "admin" => "admin_tasks#index"
  get "employees" => "users#index"
  get "new/employee" => "users#new"
  get "edit/employee" => "users#edit"



  get "etasks" => "eadmin_tasks#index"

  resources :teams



end

app/models/document.rb
class Document < ActiveRecord::Base
  belongs_to :team

  has_attached_file :file
  validates_attachment :file, content_type: { content_type: "application/pdf" },   :styles => {
    :thumb => ["200x200>", :pdf],
    :medium => ["500x500>", :png]}

    validates :title, :presence => true
    validates :file, :presence => true
    validates :team_id, :presence => true


    FileIcon = {

        :pdf => '/pdf.png',

        :doc => '/word.png'

        #... and other any file types, all like this

        }

end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: [:show, :edit, :update, :destroy]

  # GET /documents
  # GET /documents.json
  def index
    @documents = Document.all
    @users = User.all

  end

  # GET /documents/1
  # GET /documents/1.json
  def show
  end

  # GET /documents/new
  def new
    @document = Document.new
  end

  # GET /documents/1/edit
  def edit
  end

  # POST /documents
  # POST /documents.json
  def create
    @document = Document.new(document_params)
    respond_to do |format|
      ap tame_name = params[:document][:team]
      if @document.save
        format.html { redirect_to documents_url(:team_id => @document.team_id, :team => tame_name), notice: 'Document was successfully created.' }
        format.json { render :show, status: :created, location: @document }
      else
        format.html { redirect_to new_document_path(:team_id => @document.team_id), notice: 'Document not created.' }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documents/1
  # PATCH/PUT /documents/1.json
  def update
    respond_to do |format|
      ap tame_name = params[:document][:team]
      if @document.update(document_params)
        format.html { redirect_to documents_url(:team_id => @document.team_id, :team =>  tame_name ), notice: 'Document was successfully updated.' }
        format.json { render :show, status: :ok, location: @document }
      else
        format.html { redirect_to edit_document_path(:team_id => @document.team_id, :team => params[:team]), notice: 'Document was not updated.'  }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document.file = nil
    @document.save
    @document.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Document was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document
      @document = Document.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def document_params
      params.require(:document).permit(:title, :team_id, :file)
    end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_form.html.erb
<!--  FORM ELELEMNTS for Creating New Tasks and Updating Existing Tasks -->
<div class="row">
  <!-- spaceholder -->
  <div class="col s12 m12 l2">&nbsp;</div>
  <!-- form -->
  <div class="col s12 m12 l8">

    <%= form_for @document,  html: { multipart: true } do |f| %>
    <% if @document.errors.any? %>
    <div id="error_explanation">
      <h4>Please fill out the following feilds:</h4>
      <ul>
        <% @document.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>

    <div class="form-panel">
      <div class="field">
        <%= f.hidden_field :team_id, value: params[:team_id]%>
      </div>
      <div class="field">
        <%= f.hidden_field :team, value: params[:team]%>
      </div>

      <!-- name -->
      <!-- things to help with task -->
      <div class="row">
        <div class="input-field col s12">
          <%= f.text_area :title, class: "materialize-textarea" %>
          <%= f.label :title, "Whats the name of the document?" %>
        </div>
      </div>


      <div class="input-field">
          <label for="document_document">Document</label>
      <br><br>

           <%= f.file_field :file %>
     </div>

<!--
     <div class="field">
       <%= f.label :team, "For which team?"%>
       <%= f.collection_select :team, Team.order(:name),:name,:name, { include_blank: "Select a Team", disabled: 'false'}, { required: true}%>
       <p style="font-size: 0.8rem;"> <%= link_to 'OR create a new team', new_team_path %></p> <br>
     </div> -->



      <!-- buttons to save -->
      <div class="row">
        <div class="actions col s12 centered">
          <%= link_to 'Cancel', :back, class: "btn btn-large" %>
          <input type="submit" value="Submit!" class="btn btn-large" >
        </div>
      </div>


    </div>
    <% end %>
  </div>
  <!-- spaceholder -->
  <div class="col s12 m12 l2">&nbsp;</div>
</div>

app/views/documents/edit.html.erb
<div class="container">
  <div class="row">
    <div class="s12 m12 l2">&nbsp;</div>
    <div class="s12 m12 l8"><h4>Edit document details</h4></div>
    <div class="s12 m12 l2">&nbsp;</div>
  </div>
</div>
<%= render 'form' %>

app/views/documents/index.html.erb
<!-- Team  Tools -->




<!-- Team Navbar end -->
<!-- Admin Tools -->

<div class="fixed-action-btn" style="bottom: 45px; right: 24px;">

    <%= link_to '<i class="large material-icons">add</i>'.html_safe, new_document_path(:category => 1), id: "addSmallButton", class: "btn-floating btn-large teal tooltipped", 'data-tooltip': "Add Task", 'data-position': "left" %>

  <!-- <a href="add.html" class="btn-floating btn-large red tooltipped" data-position="left" data-tooltip="Add Task">
    <i class="large material-icons">add</i>
  </a> -->
  <!-- <ul>
    <li><a class="btn-floating yellow darken-1 tooltipped" data-position="left" data-tooltip="Manage Users"><i class="material-icons">perm_identity</i></a></li>
    <li><a class="btn-floating green tooltipped" data-position="left" data-tooltip="Edit Template"><i class="material-icons">recent_actors</i></a></li>
    <li><a class="btn-floating blue tooltipped" data-position="left" data-tooltip="Manage Account Settings"><i class="material-icons">settings</i></a></li>
  </ul> -->
</div>
<!-- End admin tools -->
<ul class="pagination">
  <% if can? :delete , @post%>
    <% team = @teams.find_by_name(params[:team]) %>
    <li class="waves-effect"><%= link_to 'Tasks', admin_tasks_path(:category => params[:category],:team => params[:team]) %>
    </li>
    <% else %>
    <li class="waves-effect"><%= link_to 'Tasks', eadmin_tasks_path(:category => params[:category],:team => params[:team]) %>
    </li>
   <% end %>

    <li class="waves-effect active"><a>Document</a></li>


</ul>


<!-- Wrapper for sidebar and layout -->

<div class="row">

  <!-- Content -->
  <div class="col s12 m8 l7 offset-l1">
    <div class="row top">
      <h4 style="display: inline"><%= params[:team]%>'s Documents</h4>
      <% if can? :delete , @post%>
        <%= link_to '<i class="material-icons left">add</i>Add a document</a>'.html_safe, new_document_path( :team_id => params[:team_id], :team => params[:team]), id: "addBigButton", class: "waves-effect waves-light btn show-on-large", style: "float: right"  %>
      <% end %>
    </div>



    <% if @documents.empty? %>
    <div class="row centered">
      <div class="col s12 m8">
        <div class="card-panel teal">
          <span class="white-text">
            <i class="em em-sweat_smile"></i>  Add a document for your new employees.
          </span>
        </div>
      </div>
    </div>
    <% end %>
    <!-- Start of collection for displaying documents for ADMINS -->

      <!--ADMIN VIEW  -->
      <% if can? :delete, @post %>
      <ul class="collection">
       <% @documents.where(:team_id => params[:team_id]).each do |document| %>
          <li class="collection-item avatar">
            <%= image_tag Document::FileIcon[document.file(:thumb).match(/\.(\w+)\?\d*$/)[1].try(:to_sym)], :width => "50", :class => "circle" if document.file %>
            <span class="title"><%= link_to document.title, document.file.url(:original, false), :target => "_blank" %></span>
            <p><%= document.updated_at.strftime("%e, %B, %Y %l:%M %P") %><br></p>
            <%= link_to '<i class="material-icons">edit</i>'.html_safe, edit_document_path(document, :team_id => params[:team_id], :team => params[:team]),  class: "secondary-content blue-text", style: "margin-right:50px" %>
            <%= link_to '<i class="material-icons">delete</i>'.html_safe, document_path(document),method: :delete,  class: "secondary-content blue-text", data: { confirm: 'Are you sure you want to delete this document?' } %>
          </li>
        <% end %>
      </ul>
      <% else %>
      <!--EMPLOYEE VIEW  -->
        <% team_name = current_user.user_info %>
        <% team = @teams.find_by_name(team_name) %>
        <!-- Pulls the TEAM documents -->
        <h5>Documents for <%= team_name %> Team</h5>
        <ul class="collection">
        <% @documents.where(:team_id => team.id).each do |document| %>
           <li class="collection-item avatar">
             <%= image_tag Document::FileIcon[document.file(:thumb).match(/\.(\w+)\?\d*$/)[1].try(:to_sym)], :width => "50", :class => "circle" if document.file %>
             <span class="title"><%= link_to document.title, document.file.url(:original, false), :target => "_blank" %></span>
             <p><%= document.updated_at.strftime("%e, %B, %Y %l:%M %P") %><br></p>
           </li>
         <% end %>
       </ul>
       <!-- Pulls the EVERYONE documents -->
       <h5>Documents for Everyone</h5>
       <ul class="collection">
         <% @documents.where(:team_id => 1).each do |document| %>
            <li class="collection-item avatar">
              <%= image_tag Document::FileIcon[document.file(:thumb).match(/\.(\w+)\?\d*$/)[1].try(:to_sym)], :width => "50", :class => "circle" if document.file %>
              <span class="title"><%= link_to document.title, document.file.url(:original, false), :target => "_blank" %></span>
              <p><%= document.updated_at.strftime("%e, %B, %Y %l:%M %P") %><br></p>
            </li>
          <% end %>
        </ul>
      <%end%>

      <!-- END of collection for displaying documents -->
  </div>
  <!-- End content -->

  <!-- Sidebar -->
  <div class="col s12 m4 l3 offset-l1">
    <!-- Profile card -->
    <div class="card top">
      <div class="card-content">
        <span class="card-title"> Information Centre</span>
        <p>Any documents you add here will be copied to each new hire you onboard.</p>
      </div>
    </div>


  </div>
  <!-- End Sidebar -->

</div>

app/views/documents/new.html.erb
<div class="container">
  <div class="row">
    <div class="s12 m12 l2">&nbsp;</div>
    <div class="s12 m12 l8"><h4>Upload a new document for team </h4></div>
    <div class="s12 m12 l2">&nbsp;</div>
  </div>
</div>
<%= render 'form' %>

app/views/documents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @document.title %>
</p>

<p>
  <strong>Team:</strong>
  <%= @document.team %>
</p>

<%= link_to 'Edit', edit_document_path(@document) %> |
<%= link_to 'Back', documents_path %>