config/routes.rb
Rails.application.routes.draw do


<<<<<<< HEAD
  resources :documents
=======
  resources :events
>>>>>>> events-feature
  resources :categories

  post '/attendances/create' => 'attendances#create', :as => :create_attendance
  resources :attendances

  get 'team/scaffold'

  resources :events do
    get :autocomplete_user_name, :on => :collection
  end

  resources :stakeholders

  resources :eadmin_tasks do
<<<<<<< HEAD
		  member do
		    patch :complete
		    patch :not_complete
		    patch :create
        patch :edit
		  end
		end
=======
    member do
      patch :complete
      patch :not_complete
      patch :create
    end
  end
>>>>>>> events-feature

  devise_for :views
  #Devise routes with custom registrations controller
  devise_for :users, controllers: { registrations: "registrations", sessions: "sessions" }

  resources :admin_tasks
  # get 'admin_tasks/:category' => 'admin_tasks#index'

  resources :users

  get 'users/:id/eadmin_tasks' => 'users#eadmin_tasks', :as => :user_eadmin_tasks
  get 'users/:id/promote_to_admin' => 'users#promote_to_admin', :as => :promote_user_to_admin
  get 'events/:id/attendance' => 'events#attendance', :as => :manage_event_attendance
  get "subscriptions/cancel_subscription" => "subscriptions#cancel_subscription"
  get "subscriptions/update_card" => "subscriptions#update_card"
  post "subscriptions/update_card_details" => "subscriptions#update_card_details"
  resources :subscriptions



  root to: "home#index"

  get "admin" => "admin_tasks#index"
  get "employees" => "users#index"
  get "new/employee" => "users#new"
  get "edit/employee" => "users#edit"



  get "etasks" => "eadmin_tasks#index"

  resources :teams



end

app/views/layouts/_header.html.erb
<nav>
  <div  class="nav-wrapper" style=" ">
  <% if can? :delete, @post %>
    <%# Side nav for Admin %>
<<<<<<< HEAD
    <ul id="nav-mobile" class="right hide-on-med-and-down">
          <li class=" <%= active_class(users_path) %>"><%= link_to "Our People", users_path %></li>
          <li class=" <%= active_class(edit_user_registration_path) %>"  ><%= link_to "Account Settings", edit_user_registration_path %></li>
          <li class=" "   ><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
=======
    <% if can? :delete, @post %>
      <%# DESKTOP and MOBILE %>
      <ul id="slide-out" class="side-nav">
        <img  src="/assets/site-logo.png" class="center-align responsive-img" style="margin-top:3%" alt="logo"></a>
        <li class="no-padding">
          <ul class="collapsible collapsible-accordion">
            <li>
              <a class="collapsible-header">Teams &amp; Tasks</a>
              <div class="collapsible-body">
                <ul>
                  <li class="<%= 'active' if current_page?(teams_path) %>"  ><%= link_to "Teams", teams_path %></li>
                  <li class="<%= 'active' if current_page?(admin_path) %>"  ><%= link_to "Tasks for Everybody", admin_path %></li>
                  <% @teams.each do |t| %>
                  <li><%= link_to "#{t.name} Tasks", admin_path(:team => t.name) %></li>
                  <% end %>
                </ul>
              </div>
            </li>
          </ul>
        </li>
        <li class="<%= 'active' if current_page?(events_path) %>"><%= link_to "Events", events_path %></li>
        <%# MOBILE ONLY %>
        <div class="hide-on-large-only">
          <li class="<%= 'active' if current_page?(users_path) %>"  ><%= link_to "Our People", users_path %></li>
          <li class="<%= 'active' if current_page?(edit_user_registration_path) %>"  ><%= link_to "Account Settings", edit_user_registration_path %></li>
          <li class="<%= 'active' if current_page?(destroy_user_session_path) %>"   ><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
        </div>
>>>>>>> events-feature
      </ul>

    <a  href="#" data-activates="slide-out" class="button-collapse show-on-small" ><i class="material-icons">menu</i></a>
      <%# DESKTOP  %>
      <ul id="slide-out" class="side-nav fixed #ffffff white">
        <img  src="/assets/site-logo.png" class="center-align responsive-img" style="padding:6%; margin-top:5%;" alt="logo"></a>
         <li class="no-padding">


            <ul class="collapsible collapsible-expandable ">
              <li class="">
                <a  class="bold collapsible-header active " id="#team"><span style="font-weight:900;">Teams</span></a>
                <div class="collapsible-body">
                  <ul class="team-d">
                    <li class=" text-darken-2 <%= 'active' if params[:team] == 'Everyone' %>"  ><%= link_to "Everyone", admin_path %></li>
                    <% @teams.where.not(name: 'Everyone').each do |t| %>
                      <li  id="demo" class="<%= 'active' if params[:team] == t.name %> "><%= link_to "#{t.name}", admin_path(:team => t.name) %></li>
                    <% end %>

                  </ul>
                </div>
              </li>
              <li style = "height:80px;" class="<%= active_class(teams_path) %>"  ><%= link_to '<span style="font-weight:900; margin-top:10px; ">Manage Teams</span>'.html_safe, teams_path,:style=>'line-height:40px; height:80px;'%></li>

            </ul>
           </li>
           <!-- <li class"waves-effect"><a href="#!">Events</a></li> -->

          <% else %>
            <ul id="nav-mobile" class="right hide-on-med-and-down">
              <li class=" <%= active_class(eadmin_tasks_path) %>" ><%= link_to "My Onboarding Steps ", eadmin_tasks_path %></li>
              <li class=" "   ><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
            </ul>


        <% end %>


      </ul>



    <%# END SIDE NAV %>

  </div>
</nav>

app/views/layouts/_headersignin.html.erb
  <nav style="padding-left:-240px">
    <div class="nav-wrapper">
      <div class="container">
      <div class="navbar-header">
        <%= link_to "One Rocket", root_path, class: "brand-logo" %>
      </div>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li class="<%= 'active' if current_page?(root_path) %>" ><%= link_to "Home", root_path %></li>
        <li class="<%= 'active' if current_page?(root_path) %>" ><%= link_to('Sign in', new_user_session_path) %></li>
      </ul>
      </div>
    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <!-- Compiled and minified JavaScript -->




  <title>One Rocket - Simple Employee Onboarding</title>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'circle', 'data-turbolinks-track' => true %>
  <%= favicon_link_tag 'favicon-32x32.png' %>

  <!-- Compiled and minified CSS -->
  <link href="https://afeld.github.io/emoji-css/emoji.css" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/css/materialize.min.css">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700" rel="stylesheet">

  <style>
    html {
      font-family: "Open Sans", "Roboto", sans-serif;
    }
    .top {
      margin-top: 10%;
      margin-bottom: 5%;
    }
    .centered {
      text-align: center;
      margin-left: auto;
      margin-right: auto;
    }


    .side-nav a {
      color: white;
      display: block;
      font-size: 1rem;
      height: 34px;
      line-height: 34px;
      padding: 0 30px;

  }
  </style>

  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<body>
  <header>
    <% if user_signed_in? %>
      <%= render 'layouts/header' %>
    <% else %>
      <%= render 'layouts/headersignin' %>
    <% end %>

    <% flash.each do |key, value| %>
      <script>
        Materialize.toast("<%= value %>", 3000);
      </script>
    <% end %>


  </header>

  <main>
    <div class="container" style="width: 90%;">

    <%= yield %>
    </div>
  </main>

<!-- Modal -->
<!-- <footer class="page-footer">
  <div class="footer-copyright">
    <div class="container">
      © 2016 One Rocket
    </div>
  </div>
</footer> -->

<!-- All the javascripts -->
<script type="text/javascript">
  $(document).ready(function(){
    $(".dropdown-button").dropdown();
    $(".button-collapse").sideNav();
    $('.collapsible').collapsible();
    $('select').material_select();
    $('ul.tabs').tabs();
<<<<<<< HEAD

    if ( $( "#demo" ).hasClass('active')) {

        $( "#head-demo" ).addClass('active')

    }

=======
    $('.datepicker').pickadate({
      selectMonths: true, // Creates a dropdown to control month
      selectYears: 15 // Creates a dropdown of 15 years to control year
    });
>>>>>>> events-feature
  })
</script>
<script type="text/javascript" src="https://js.stripe.com/v2/"></script>
<script>

  Stripe.setPublishableKey('pk_test_vDSiuOkeTaV8mLnuOgqAQyWd');

</script>

</body>

</html>